Repository Transconlang/translang, pull requests merged in 2024-11, with the labels that each got.

#48 Generate serialized language spec
  .github/workflows/gen-json-spec.yml
  README.md
  rawspec/.gitkeep
  rawspec/0-complete.json
  rawspec/adjectives.json
  rawspec/adverbs.json
  rawspec/conjunctions.json
  rawspec/interjections.json
  rawspec/nouns.json
  rawspec/numbers.json
  rawspec/prefixes.json
  rawspec/prepositions.json
  rawspec/pronouns.json
  rawspec/suffixes.json
  rawspec/verbs.json
  scripting/.gitignore
  scripting/.prettierrc
  scripting/index.ts
  scripting/package-lock.json
  scripting/package.json
  scripting/tsconfig.json
  scripting/types.ts
Labels: enhancement, help wanted

#54 Update spec to have headers & subsections in individual parts
  Vocabulary/Pronouns.md
  rawspec/0-complete.json
  rawspec/adjectives.json
  rawspec/adverbs.json
  rawspec/conjunctions.json
  rawspec/interjections.json
  rawspec/nouns.json
  rawspec/numbers.json
  rawspec/prefixes.json
  rawspec/prepositions.json
  rawspec/pronouns.json
  rawspec/suffixes.json
  rawspec/verbs.json
  scripting/index.ts
  scripting/types.ts
Labels: bug, enhancement

#56 ensure markdown compatibility with parser
  Vocabulary/Suffixes.md
  scripting/index.ts
Labels: bug

#58 added word for love verb and infinitive prefix
  Vocabulary/Nouns.md
  Vocabulary/Suffixes.md
  Vocabulary/Verbs.md
  rawspec/0-complete.json
  rawspec/suffixes.json
  rawspec/verbs.json
Labels: incomplete, addition

#69 Update examples
  Examples.md
Labels: semantics

#70 add contributing guide
  CONTRIBUTING.md
  Formatting.md
  Grammar.md
  Phonetics.md
  README.md
Labels: restructure, semantics
