Repository Transconlang/translang, pull requests merged in 2024-12, with the labels that each got.

#71 add miremire for gray
  Vocabulary/Adjectives.md
Labels: addition

#72 Update Adjectives.md
  Vocabulary/Adjectives.md
Labels: addition

#73 move "very" to adverbs
  Vocabulary/Adjectives.md
  Vocabulary/Adverbs.md
Labels: addition

#74 Adding in suranto for same
  Vocabulary/Adjectives.md
Labels: addition

#66 Parser upgrade
  .gitattributes
  .github/workflows/gen-json-spec.yml
  .prettierrc
  Formatting.md
  Obscurisms.md
  Vocabulary/Adjectives.md
  Vocabulary/Adverbs.md
  Vocabulary/Conjunctions.md
  Vocabulary/Interjections.md
  Vocabulary/Nouns.md
  Vocabulary/Numbers.md
  Vocabulary/Prefixes.md
  Vocabulary/Prepositions.md
  Vocabulary/Pronouns.md
  Vocabulary/Suffixes.md
  Vocabulary/Verbs.md
  rawspec/.gitkeep
  rawspec/0-complete.json
  rawspec/adjectives.json
  rawspec/adverbs.json
  rawspec/conjunctions.json
  rawspec/interjections.json
  rawspec/nouns.json
  rawspec/numbers.json
  rawspec/prefixes.json
  rawspec/prepositions.json
  rawspec/pronouns.json
  rawspec/suffixes.json
  rawspec/verbs.json
  run-scripts.sh
  scripting/index.ts
  scripting/package.json
  scripting/types.ts
  scripting/validate.ts
Labels: critical, scripting, restructure, semantics

#78 improved personal pronoun descriptions
  Vocabulary/Pronouns.md
Labels: addition

#82 Improved explanation of verb tense suffixes
  Grammar.md
Labels: semantics
